version: "3.1"
services:
  postgres:
    image: postgres
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg:/docker-entrypoint-initdb.d/
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=docker
    restart: unless-stopped
# This is my rest api app*****************************************
  myfirstapp:
    image: myfirst
    network_mode: bridge
    container_name: myfirst
    expose:
      - 8080
    ports:
      - 8081:8080
    volumes:
          - /home/otlokan/Desktop:/var/tmp
    restart: unless-stopped
volumes:
  postgres-data:
